name: MaintainableCSS | Scalable and modular CSS | By Adam Silver
markdown: kramdown
url: http://maintainablecss.com
include: ['_pages']
collections:
  chapters:
    output: true
    permalink: /:collection/:title/
description: Write CSS without worrying that overzealous, pre-existing styles will cause problems. MaintainableCSS is an approach to writing modular, scalable and of course, maintainable CSS.