name: Maintainable CSS | Scalable and modular CSS | By Adam Silver
markdown: kramdown
url: http://maintainablecss.com
include: ['_pages']
collections:
  chapters:
    output: true
    permalink: /:collection/:title/